---
- name: install InfluxData yum repo
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo
    mode: 0644
    owner: root
    group: root

- name: install Telegraf
  yum:
    name: telegraf
    state: present

- name: install Telegraf config file
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: fix httpd access log permissions
  file:
    path: /var/log/httpd
    mode: 0701
  when: hosttype == 'hgweb'

- name: start the Telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
