---
- name: create cinnabarclone directory if it doesn't exist
  file:
    path: /var/lib/git-cinnabar/mercurial
    state: directory

- name: clone git-cinnabar for the cinnabarclone mercurial extension
  get_url:
    url: https://raw.githubusercontent.com/glandium/git-cinnabar/28bb4acb178e7a6326880ad39478edcc8a3c955c/mercurial/cinnabarclone.py
    dest: /var/lib/git-cinnabar/mercurial/cinnabarclone.py
    sha256sum: 15910a23102bb0b92fb1b8cba8ac07be6ef651b36f3ae6795ee4c910a496221d
