---
- name: Confirm that another form of Docker isn't already installed
  yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent
  become: true

- name: Add Docker repository
  yum_repository:
    name: docker
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  become: true

- name: Install Docker
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
    state: latest
  become: true

- name: Enable Docker in Systemd
  service:
    name: docker
    state: started
    enabled: true
  become: true
