---
- hosts: hgweb-mirrors
  tasks:
  - name: apply hgweb role with replication filters
    include_role:
      name: hg-web
    vars:
      # We have to use hostvars to reference variables on other hosts.
      # slurp captures content in base64 encoded form. Decode it
      # before it is passed in.
      mirror_private_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_private_key.content | b64decode }}"
      mirror_host_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_host_key.content | b64decode }}"
      # hg-zlb.vips.scl3.mozilla.com resolves to multiple IPs.
      mirror_ips: ["63.245.215.25", "63.245.215.102"]
      vct_node: "{{ lookup('file', '../.vctnode') }}"
      # Comment out these variables for now, since they are managed by
      # RelOps puppet and we don't need them on the mirror instances
#            chroot_mozbuild_exists: "{{ hostvars['localhost'].chroot_mozbuild.stat.exists }}"
#            bloxtool_user: "{{ (bloxtool_config.content | b64decode | from_json).user }}"
#            bloxtool_password: "{{ (bloxtool_config.content | b64decode | from_json).password }}"
#            bloxtool_url: "{{ (bloxtool_config.content | b64decode | from_json).url }}"
#            s3_cache_access_key_id: "{{ (s3cacher_config.content | b64decode | from_json).access_key_id }}"
#            s3_cache_secret_key: "{{ (s3cacher_config.content | b64decode | from_json).secret_access_key }}"
      replication_filters: True

  - name: apply monitoring-agent role
    include_role:
      name: monitoring-agent

  # TODO: refactor hg-web role so we don't install unnecessary services in the first place
  - name: turn off services considered irrelevant to mirror hosts
    service: name={{ item }}
             enabled=no
             state=stopped
    with_items:
      # These hosts will never serve to Mozilla offices, and don't
      # have bloxtool credentials. No need for them here.
      - mozilla-ip-scraper.service
      - mozilla-ip-scraper.timer
