---
- hosts: hgssh-prod-master
  gather_facts: no
  tasks:
    - name: obtain previously-deployed changeset
      slurp: src=/etc/mercurial/deployed_vct_changeset
      register: previous_vct_node

    # We need to write this out on clients.
    - name: capture mirror key
      slurp: src=/etc/mercurial/mirror
      register: mirror_private_key

    - name: capture host key
      slurp: src=/etc/mercurial/ssh/ssh_host_rsa_key.pub
      register: mirror_host_key

    - name: capture hg-deploy-bot password
      slurp: src=/repo/hg/hg-deploy-bot.pw
      register: hg_deploy_bot_pw

- hosts: localhost
  gather_facts: no
  tasks:
    - name: verify deploying changeset is available on server
      command: hg -R {{ vct }} log -r {{ lookup('file', '../.vctnode') }} -T '{phase}'
      register: vct_node_phase

    - name: require public vct node
      fail: msg='the v-c-t changeset being deployed is not public; cannot continue'
      when: vct_node_phase.stdout != 'public'

    - name: capture changes since last time
      local_action: command hg --cwd {{ vct }} log -r {{ hostvars[groups['hgssh-prod-master'][0]].previous_vct_node.content | b64decode }}::{{ lookup('file', '../.vctnode') }} -T '{node|short} {desc|firstline}\n'
      register: vct_changes

    - name: check if mozbuild chroot is available
      stat: path={{ vct }}/chroot_mozbuild/chroot.tar.gz
      register: chroot_mozbuild

    - block:
      - name: notify IRC of deployment
        irc: server=irc.mozilla.org
             port=6697
             use_ssl=true
             channel="#vcs"
             nick=hg-deploy-bot
             color=red
             msg="Started deploy of revision {{ lookup('file', '../.vctnode') }} to hg.mozilla.org; previous {{ hostvars[groups['hgssh-prod-master'][0]].previous_vct_node.content | b64decode }}"
             passwd="{{ hostvars[groups['hgssh-prod-master'][0]].hg_deploy_bot_pw.content | b64decode }}"
        run_once: true
      rescue:
        - debug:
            msg: "Started deploy of revision {{ lookup('file', '../.vctnode') }} to hg.mozilla.org; previous {{ hostvars[groups['hgssh-prod-master'][0]].previous_vct_node.content | b64decode }}"

- import_playbook: deploy-hgweb.yml
  when: skip_hgweb == False

- import_playbook: deploy-hgssh.yml
  when: skip_hgssh == False

- import_playbook: deploy-mirrors.yml
  when: skip_mirrors == False

- hosts: localhost
  gather_facts: no
  tasks:
    - block:
      - name: notify IRC of deployment
        irc: server=irc.mozilla.org
             port=6697
             use_ssl=true
             channel="#vcs"
             nick=hg-deploy-bot
             color=red
             msg="Finished deploy of hooks and extensions to hg.mozilla.org"
             passwd="{{ hostvars[groups['hgssh-prod-master'][0]].hg_deploy_bot_pw.content | b64decode }}"
        run_once: true
      rescue:
        - debug:
            msg: "Finished deploy of hooks and extensions to hg.mozilla.org"
