---
- hosts: "{{ var_hostgroup | default('hgweb-mirrors') }}"
  tasks:
  - name: set SELinux to permissive mode
    selinux:
      policy: targeted
      state: permissive

  - name: apply hgweb role with replication filters
    include_role:
      name: hg-web
    vars:
      httpd_max_clients: 25
      # We have to use hostvars to reference variables on other hosts.
      # slurp captures content in base64 encoded form. Decode it
      # before it is passed in.
      mirror_private_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_private_key.content | b64decode }}"
      mirror_host_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_host_key.content | b64decode }}"
      # The Zeus load balancer in MDC1 resolves to multiple IPs.
      mirror_ips: ["63.245.215.25", "63.245.215.102"]
      vct_node: "{{ lookup('file', '../.vctnode') }}"
      replication_filters: mirror

  - name: apply monitoring-agent role
    include_role:
      name: monitoring-agent
    vars:
      hosttype: hgweb

