---
- hosts: "{{ var_hostgroup | default('hgweb-prod') }}"
  tasks:
  - name: capture bloxtool config
    slurp: src=/etc/mercurial/bloxtool.json
    register: bloxtool_config

  - name: apply hg-web role
    include_role:
      name: hg-web
    vars:
      # We have to use hostvars to reference variables on other hosts.
      # slurp captures content in base64 encoded form. Decode it
      # before it is passed in.
      mirror_private_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_private_key.content | b64decode }}"
      mirror_host_key: "{{ hostvars[groups['hgssh-prod-master'][0]].mirror_host_key.content | b64decode }}"
      # The Zeus load balancer in MDC1 resolves to multiple IPs.
      mirror_ips: ["63.245.215.25", "63.245.215.102"]
      vct_node: "{{ lookup('file', '../.vctnode') }}"
      chroot_mozbuild_exists: "{{ hostvars['localhost'].chroot_mozbuild.stat.exists }}"
      bloxtool_user: "{{ (bloxtool_config.content | b64decode | from_json).user }}"
      bloxtool_password: "{{ (bloxtool_config.content | b64decode | from_json).password }}"
      bloxtool_url: "{{ (bloxtool_config.content | b64decode | from_json).url }}"

  - name: apply monitoring-agent role
    include_role:
      name: monitoring-agent
    vars:
      hosttype: hgweb
