---
- name: install supervisor config
  copy: src=supervisor-{{ item }}.conf
        dest=/etc/supervisor.d/{{ item }}.conf
        owner=root
        group=root
        mode=0644
  with_items:
    - docker
    - docker-kafkabroker

# Docker isn't running systemd. Remove the rsyslog config file telling
# rsyslog to bind to /run/systemd/journal/syslog so it binds to /dev/log
# by default and logging tools work.
- name: remove systemd syslog config
  file: path=/etc/rsyslog.d/listen.conf
        state=absent

# Hack up rsyslog config so it works without systemd
- name: remove systemd from rsyslog
  replace: dest=/etc/rsyslog.conf
           regexp='^\$ModLoad imjournal.*'
           replace=''

- name: enable local syslog logging
  replace: dest=/etc/rsyslog.conf
           regexp='^\$OmitLocalLogging on'
           replace='$OmitLocalLogging off'

- name: disable syslog journal file
  replace: dest=/etc/rsyslog.conf
           regexp='^\$IMJournalStateFile'
           replace='#$IMJournalStateFile'

- name: install Docker support files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - enable-fastannotate
    - entrypoint.py
    - set-config-option
    - set-mirror-key.py

- name: Install IP address documents for prioritizing streamed clone bundles
  copy: src={{ item }} dest=/var/hg/{{ item }} owner=hg group=hg mode=0644
  with_items:
    - moz-ip-ranges.txt
    - aws-ip-ranges.json
    - gcp-ip-ranges.txt
    - test_instance_data.json
